global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'unravel-prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'unravel-spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['unravel-spring-app:8080']