apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds
    access: proxy
    url: http://unravel-prometheus:9090
    isDefault: true
    version: 1
    editable: true